### ISSUE TITLE
download_filings.py failing with xbrlrss-2016-07.xml (or later)

### ISSUE THREAD

**Issue by keithmackay** [altova/sec-edgar-tools#1]
Hi folks -
I have used these scripts reliably through 2016-06--great stuff!

Do I need to be configuring things differently, somehow, for usage beginning in July 2016? Are there new schemas I should be including, or something along those lines?

Download_feeds.py still works for me, but download_filings.py now fails on anything 2016-07 or later.

I run the script as follows:
RaptorXMLXBRL.exe script C:\SECDB-master\scripts\download_filings.py C:\SECDB-master\feeds\xbrlrss-2016-07.xml

When run, the script generates the following error (repeated many times, occurring roughly every 30 rows in the xml file):

Error: file:///C:/SECDB-master/feeds/xbrlrss-2016-07.xml:2791
: Attribute 'edgar:inlineXBRL' is not allowed in element <edgar:xbrlFile>
  Details:
    cvc-complex-type.3.2.1: Complex type definition '{anonymous}' of element <ed
gar:xbrlFile> does not allow attribute 'edgar:inlineXBRL' and has no attribute w
ildcard.
    cvc-type.3.2: Element <edgar:xbrlFile> is not valid with respect to type def
inition '{anonymous}'.
    cvc-elt.5: The element <edgar:xbrlFile> is not valid with respect to the act
ual type definition '{anonymous}'.
    cvc-assess-elt.1.1: Strict assessment of element <edgar:xbrlFile> with gover
ning element declaration 'edgar:xbrlFile' failed.

Traceback as follows:

Traceback (most recent call last):
  File "C:\SECDB-master\scripts\download_filings.py", line 120,
 in <module>
    main()
  File "C:\SECDB-master\scripts\download_filings.py", line 116,
 in main
    download_filings(feedpath,args)
  File "C:\SECDB-master\scripts\download_filings.py", line 59,
in download_filings
    for filing in feed_tools.read_feed(feedpath):
  File "C:\SECDB-master\scripts\feed_tools.py", line 195, in re
ad_feed
    feed = load_feed(filepath)
  File "C:\SECDB-master\scripts\feed_tools.py", line 121, in lo
ad_feed
    raise Error(error)
NameError: name 'Error' is not defined

**Comment by xmldev** [comment]
hi keithmackay,

we've updated the schema to allow `edgar:inlineXBRL`  - thanks for reporting!

**Comment by keithmackay** [comment]
Works great -- I'm running it now. Thanks for the quick fix!

Best regards,
Keith
